### ISSUE TITLE
Lens 5 compatibility

### ISSUE THREAD

**Issue by edokan** [pashevskii/debug-pods-lens-extension#7] opened 2021-06-30 06:24 UTC
Hello,

Can you add support for Lens 5? or guide me through it, so I can try.

**Comment by pashevskii** [comment] 2021-06-30 08:56
Hi
Thank you for the issue. I'll update the plugin soon

**Comment by gaurav9822** [comment] 2021-07-09 14:36
@pashevskii please notify once it is compatible with lens 5.

**Comment by pashevskii** [comment] 2021-07-14 07:37
JFY, the update is almost done, but, unfortunately, there is a [issue](https://github.com/lensapp/lens/issues/3375) which blocks my work. I hope it will be resolved in a short time.

**Comment by pashevskii** [comment] 2021-07-20 10:06
@gaurav9822  Good news! Lens 5 compatible version is released.
https://github.com/pashevskii/debug-pods-lens-extension/releases/download/0.1.3/lens-debug-tools-0.1.3.tgz

**Comment by martincollado** [comment] 2021-07-20 11:14
Installed from the tgz file:
![image](https://user-images.githubusercontent.com/61695048/126314767-b4d133f8-a881-430f-827b-a997bd2bddd5.png)

Lens version: v5.1.2

**Comment by pashevskii** [comment] 2021-07-20 11:24
![image](https://user-images.githubusercontent.com/53330707/126315454-166f96c0-0788-474a-aee7-315925475c4e.png)
It is strange, could you please provide a little bit more info about the environment? OS, How Lens was installed (from sources, rpm, snap). Did you try to restart Lens? (there are some bugs related with installing new extension)

**Comment by martincollado** [comment] 2021-07-20 12:01
Sure!
OS: MacOS Big Sur 11.4 - Apple M1
Lens was installed from the website with de dmg file. I've restarted the app and nothing changes on that message.

**Comment by pashevskii** [comment] 2021-07-20 12:02
Thanks, I'll try to reproduce it

**Comment by pashevskii** [comment] 2021-07-20 12:42
@mcolladoio I found the root cause of the issue (it looks like 5.1.2 release uses 5.1.1 extension dependencies). It seems it is a bug on the Lens side, I temporarily downgraded dependencies in tgz file, please try to reinstall the extension by the same link.

**Comment by martincollado** [comment] 2021-07-21 06:43
Correct! @pashevskii 
![image](https://user-images.githubusercontent.com/61695048/126443466-fef5bfc6-82ec-44b2-90ed-af0867a083ab.png)

**Closed** 2021-07-22 07:04 UTC
